### ISSUE TITLE
Issue with recording CCX Users

### ISSUE THREAD

**Issue by shakka1244** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#38]
I ran the DLAU for a customer and it came back with some strange results. They have 4 users registered in their Domino Directory (CCB) and thousands of external users that access via a browser registered in a directory catalog (CCX) but only a 141 of these CCX users are active.

When I ran the tool, I got these results showing 145 CCB users - I'm not sure if this is correct but my understanding would be 4 CCB and 141 CCX.

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/32568344/2f8d88c2-ee55-427f-ba60-45e8f297ab40)

![image](https://github.com/HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU/assets/32568344/5ebbe348-fea9-4cab-84d9-8d1414e6bef7)

**Comment by regelmol** [comment]
I suggest you check those documents under "User information" for additional information. An external user is only qualified for a CCX license when he's got absolutely nowhere more than author access to any database. Probably there are some databases where the -DEFAULT- access is higher. 
I've found for example statreps or IWA forms databases with a higher default access. In order to count those users correctly you have to fix all of those (catalog.nsf would be a good start to have a look at).

**Comment by thampel** [comment]
Does not seem to be a problem in the tool itself, but more a matter of understanding the results.
If you think the numbers are incorrect we can review your environment together, just [open a support ticket](https://support.hcltechsw.com/csm) so that we can talk directly.
