### ISSUE TITLE
The License Tracking task is not running

### ISSUE THREAD

**Issue by bels-ap** [HCL-TECH-SOFTWARE/domino-license-analysis-utility-DLAU#59]
DLAU v1.2 - Observations report that the license tracking task is not running on our cluster servers. However the setting is configured correctly in a configuration document which is applied to the server group.

**Comment by thampel** [comment]
That seems to happen when using a configuration document where a group is being used. We are going to track this as a bug + will be fixing it.

**Comment by bels-ap** [comment]
since this didn't make it into 1.2.1, is this bug only a "cosmetic" issue or is DLAU not analyzing the data from the servers using a group in the configuration document?

**Comment by Volue-Jimmy** [comment]
We have this same problem in our company.  DLAU is relatively non functional,  But I think the problem is deeper than this.  We are not getting regular updates into UserLicense.nsf even though we have the Licence Tracker enabled in our config docs for 4 servers in our domain.  It's unclear to me though if License Tracker is not kicking off the admin request, or whether the License.ncf is not recording access to the servers properly.  I don't know how to tell if the later is the problem.  I have an open case at HCL but so far, not getting anywhere. (Domino 12.0.1 FP1, this is because of a problem with single category views on 12.0.2. FP3)

**Comment by thampel** [comment]
@Volue-Jimmy Hi Jim, if this still is an issue, lets talk please. (you might still have my number)

**Comment by GulfCoach** [comment]
Hi,
I just had a cluster with a group configuration document, where there is no userlicenses.nsf. License Tracking is enabled
In the Default config document it is  also enabled .
Version is 12.02 FP3 HF33
best regards from Hamburg
Yours Ulf
